spring:
  session:
    timeout: 10m
    jdbc:
      initialize-schema: always
  jta:
    atomikos:
      datasource:
        min-pool-size: ${JDBC_CONNECTION_POOL_MIN}
        max-pool-size: ${JDBC_CONNECTION_POOL_MAX}
      properties:
        enable-logging: false
        log-base-name: VAULT_XA
        log-base-dir: /tmp/jta

    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${JDBC_HOST}:${JDBC_PORT}/${JDBC_DATABASE}?reWriteBatchedInserts=true
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
logging:
  level:
    root: info
    app: info
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: warn
    org.springframework.web: info
    org.springframework.transaction: error
    org.apache.activemq: error
    com.atomikos.jdbc.AtomikosConnectionProxy: error
    org.hibernate.jpa.internal.util.LogHelper: info