services:
  postgresql:
    image: postgres:16
    pull_policy: missing
    entrypoint: [ "docker-entrypoint.sh", "--max-prepared_transactions=200" ]
    restart: always
    expose: [ "5432" ]
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/docker-entrypoint-initdb.d"
    healthcheck:
      test: pg_isready -U app-user -d app
    environment:
      POSTGRES_PASSWORD: "change-me"
  artemis:
    image: apache/activemq-artemis:latest-alpine
    restart: on-failure
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - "./data/artemis/:/var/lib/artemis-instance/etc-override"
  app:
    image: ghcr.io/zafarius/app:0.1.0-snapshot
    volumes:
      - data:/application/data:rw
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      JDBC_HOST: postgresql
      JDBC_PORT: 5432
      JDBC_DATABASE: app
      JDBC_USERNAME: app-user
      JDBC_PASSWORD: vaultMaster123
      JDBC_CONNECTION_POOL_MIN: 5
      JDBC_CONNECTION_POOL_MAX: 20
    depends_on:
      - postgresql
volumes:
  data: