/*
 * This file was generated by the Gradle 'init' task.
 */
project.version = project.findProperty("projVersion") ?: "0.1.0-SNAPSHOT"

plugins {
    id("buildlogic.java-library-conventions")
    alias(libs.plugins.openapi.generator)
}

dependencies {
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.jakarta.validation)
    implementation(libs.openapitools.jackson)
    implementation(libs.spring.web)
    implementation(libs.swagger.annotation)

    compileOnly(libs.jakarta.servlet.api)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.spring.boot.starter.test)
}

openApiMeta {
    generatorName = "tracker-webservice-contracts"
    packageName = "app.webservice.tracker"
    outputFolder = "${layout.buildDirectory.get()}/meta"
}

openApiValidate {
    inputSpec = "${layout.projectDirectory}/verve-v1.0.yaml"
    recommend = true
}

openApiGenerate {

    generatorName = "spring"
    library = "spring-boot"
    inputSpec = "${layout.projectDirectory}/verve-v1.0.yaml"
    outputDir = "${layout.buildDirectory.get()}/generate-resources/openapi"

    apiPackage = "app.webservice.contracts.tracker"
    invokerPackage = "app.webservice.tracker"
    modelPackage = "app.verve.model"

    configOptions.put("interfaceOnly", "true")
    configOptions.put("useTags", "true")
    configOptions.put("skipDefaultInterface", "true")
    configOptions.put("useJakartaEe", "true")
    configOptions.put("useSpringBoot3", "true")

}

// Specify path to generated sources
sourceSets {
    main {
        java {
            srcDir( "${layout.buildDirectory.get()}/generate-resources/openapi")
        }
    }
}

//rename jar verve
tasks.getByName<Jar>("jar") {
    archiveBaseName = "tracker-webservice-contracts"
}