openapi: "3.0.0"
info:
  version: 1.0.0
  title: verve
servers:
  - url: http://localhost:8080/v1
paths:
  /verve/accept:
    get:
      summary: Accept request.
      operationId: getAccept
      tags:
        - verve
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
        - in: query
          name: endpoint
          required: false
          schema:
            type: string
            pattern: "^(http|https)://.*"
      responses:
        200:
          description: Request accepted.
          content:
            application/json:
              schema:
                type: string
        400:
          description: Request malformed.
        406:
          description: Proceeding failed. Hint - Endpoint not reachable
    post:
      summary: Accept request.
      operationId: postAccept
      tags:
        - verve
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: integer
      responses:
        200:
          description: Request accepted.
          content:
            application/json:
              schema:
                type: string
        400:
          description: Request malformed.