/*
 * This source file was generated by the Gradle 'init' task
 */
package app;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class Application {
    public static void main(final String[] args) {

        SpringApplication.run(Application.class, args);
    }
}
