/*
 * This file was generated by the Gradle 'init' task.
 */
project.version = project.findProperty("projVersion") ?: "0.1.0-SNAPSHOT"

plugins {
    id("buildlogic.java-library-conventions")
    alias(libs.plugins.lombok)
}

dependencies {
    implementation(project(":tracker:domain"))

    implementation(project(":common:domain"))
    implementation(project(":common:jms-config"))

    implementation(libs.spring.boot.starter.artemis)
    implementation(libs.spring.boot.starter.validation)
    implementation(libs.spring.boot.starter.data.jpa)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.spring.boot.starter.test)
}

//rename jar file
tasks.getByName<Jar>("jar") {
    archiveBaseName = "tracker-jms"
}